gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: '%env(int:REFRESH_TOKEN_TTL)%'
  ttl_update: true
  user_identity_field: token
  user_provider: App\Security\UserProvider
