image: php:7.4-fpm

definitions:
  services:
    postgres:
      image: postgres:12.11
      environment:
        POSTGRES_DB: 'phos_test_db'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'phos123!'

  steps:
    - step: &checks
        name: Checks
        script:
          - apt-get update && apt-get install -y unzip git
          - pecl install xdebug-2.9.1
          - docker-php-ext-enable xdebug
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - curl -sS https://get.symfony.com/cli/installer | bash
          - composer install
          - mkdir -p config/jwt
          - openssl genpkey -out config/jwt/private.pem -algorithm rsa -pkeyopt rsa_keygen_bits:4096
          - openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout
          - vendor/bin/phpunit --testsuite Unit --coverage-clover=coverage.xml
          - vendor/bin/phpstan --memory-limit=-1
          - /root/.symfony5/bin/symfony check:security
        artifacts:
          - coverage.xml
    - step: &sonar
        name: SonarQube analysis
        script:
          - pipe: sonarsource/sonarqube-scan:1.0.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}

pipelines:
  default:
    - step: *checks
  branches:
    development:
      - step: *checks
      - step: *sonar
  custom:
    pact_consumer:
      - variables:
          - name: Branch
            default: development
      - step: *checks
      - step:
          name: Run Pact Consumer Tests
          script:
            - echo "Running Consumer tests on branch $Branch"
            - vendor/bin/phpunit --testsuite="Api Service Consumer Tests"

