link_password_reset_v2:
  path: /link/v2/password/reset/{token}
  methods: GET
  controller: App\Controller\V2\Account\UserController::resetPasswordForm
  requirements:
    token: '^[a-zA-Z0-9]$'

api_user_reset_password:
  path: /v2/user/reset_password
  methods: POST
  controller: App\Controller\V2\Account\UserController::resetPassword

internal_force_logout_username:
  path: /internal/force-logout/by-username/{username}
  methods: POST
  controller: App\Controller\V2\Account\UserController::forceLogoutUser

internal_force_logout_device_id:
  path: /internal/force-logout/by-device-id/{deviceId}
  methods: POST
  controller: App\Controller\V2\Account\UserController::forceLogoutDevice

internal_login:
  path: /internal/login/{userToken}/{deviceId}
  methods: POST
  controller: App\Controller\V2\Account\UserController::login
