monolog:
  channels: ['communication_log','device_audit_log']
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
      formatter: monolog.formatter.custom_logstash
    elasticsearch:
      type: elasticsearch
      ignore_error: true
      elasticsearch:
        host: '%env(resolve:ELASTICSEARCH_HOST)%'
        port: '%env(resolve:ELASTICSEARCH_PORT)%'
        transport: '%env(resolve:ELASTICSEARCH_TRANSPORT)%'
        user: 'a'
        password: 'a'
      index: 'communication_log'
      channels: ['communication_log']
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]
      formatter: monolog.formatter.custom_logstash
