parameters:
  type: 'phos'
  ENCRYPTION: '%env(ENCRYPTION)%'
  REQUEST_VERIFICATION: '%env(REQUEST_VERIFICATION)%'
  env(ENCRYPTION): 'no'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\EntityManager\RefreshTokenManager:
    public: true
    arguments:
      - '@gesdinet.jwtrefreshtoken.object_manager'
      - '%gesdinet.jwtrefreshtoken.refresh_token.class%'

  app.aws_encoder:
    class: App\JwtEncoder\AwsEncoder

  gesdinet.jwtrefreshtoken.refresh_token_manager:
    class: App\EntityManager\RefreshTokenManager
    public: true
    arguments: [ '@doctrine.orm.default_entity_manager', 'Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken']

  Aws\Kms\KmsClient:
    autowire: false
    public: true

  Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface:
    autowire: false
    public: true

  GuzzleHttp\ClientInterface:
    public: true

  Symfony\Component\HttpFoundation\RequestStack:
    public: true

  Symfony\Component\Messenger\MessageBusInterface:
    public: true